[build-system]
requires = [ "flit_core >=3.2,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "bayanat"
version = "2.1.0"
description = "Bayanat data management system"
requires-python = ">=3.8"
readme = "README.md"
dependencies = [ "amqp==5.2.0", "appnope==0.1.4", "arrow==1.3.0", "Babel==2.15.0", "backcall==0.2.0", "bcrypt==4.1.3", "bleach==6.1.0", "blinker==1.8.2", "boto3==1.34.100", "botocore==1.34.100", "celery==5.4.0", "certifi==2024.7.4", "cffi==1.16.0", "chardet==5.2.0", "click==8.1.7", "cryptography==43.0.1", "decorator==5.1.1", "dnspython==2.6.1", "docutils==0.21.2", "email-validator==2.1.1", "Flask-Babel==4.0.0", "Flask-Login==0.6.3", "Flask-Principal==0.4.0", "flask-redis==0.4.0", "Flask-Script==2.0.6", "flask-security-too==5.4.1", "Flask-Session==0.8.0", "flask-shell-ipython==0.5.1", "Flask-SQLAlchemy==3.0.3", "Flask-WTF==1.2.1", "Flask==2.3.2", "GeoAlchemy2==0.15.1", "greenlet==3.0.3", "idna==3.7", "importlib-metadata==7.1.0", "itsdangerous==2.2.0", "jedi==0.19.1", "Jinja2==3.1.4", "jmespath==1.0.1", "kombu==5.3.7", "Mako==1.3.3", "MarkupSafe==2.1.5", "more-itertools==10.2.0", "numpy==1.26.4", "oauthlib==3.2.2", "openpyxl==3.1.2", "packaging==24.0", "pandas==2.1.1", "parso==0.8.4", "passlib==1.7.4", "pdf2image==1.17.0", "pexpect==4.9.0", "pickleshare==0.7.5", "Pillow==10.3.0", "prompt-toolkit==3.0.43", "ptyprocess==0.7.0", "pycparser==2.22", "pydantic==2.8.2", "pyexifinfo==0.4.0", "Pygments==2.18.0", "pyparsing==3.1.2", "pypdf==4.2.0", "PyQRCode==1.2.1", "pytesseract==0.3.10", "python-dateutil==2.9.0.post0", "python-docx==1.1.2", "python-dotenv==1.0.1", "python-editor==1.0.4", "pytz==2024.1", "redis==5.0.4", "requests==2.32.0", "setuptools==74.1.1", "s3transfer==0.10.1", "Shapely==2.0.4", "shortuuid==1.0.13", "six==1.16.0", "speaklater==1.3", "SQLAlchemy==1.4.46", "traitlets==5.14.3", "Unidecode==1.3.8", "urllib3==2.2.2", "uWSGI==2.0.26", "vine==5.1.0", "wcwidth==0.2.13", "webencodings==0.5.1", "Werkzeug==3.0.3", "WTForms==3.1.2", "zipp==3.19.1", "qrcode==7.4.2", "psycopg2==2.9.9", "setuptools==74.1.1", "weasyprint==62.1", "zxcvbn==4.4.28", "webauthn==2.1.0", "Flask-DebugToolbar==0.15.1",]
[[project.authors]]
name = "SJAC"
email = "tech@syriaaccountability.org"

[project.license]
file = "license.txt"

[project.urls]
Home = "https://bayanat.org"


[tool.bayanat]
venv_path = "env"  


[tool.black]
line-length = 100
target-version = [ "py38", "py39", "py310", "py311", "py312",]
include = "\\.pyi?$"
exclude = "/(\n    \\.eggs\n  | \\.git\n  | \\.hg\n  | \\.mypy_cache\n  | \\.nox\n  | \\.pants.d\n  | \\.pytype\n  | \\.ruff_cache\n  | \\.svn\n  | \\.tox\n  | \\.venv\n  | \\.env\n  | __pypackages__\n  | _build\n  | buck-out\n  | build\n  | dist\n  | node_modules\n  | venv\n)/\n"

[tool.flit.module]
name = "enferno"

[tool.flit.sdist]
include = [
    "enferno/**/*",
    "LICENSE",
    "README.md",
    "run.py",
    "docker-compose*.yml",
    ".env-sample",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "dev-requirements.txt",
    "pytest.ini",
    "requirements.txt",
    ".pre-commit-config.yaml",
    ".prettierrc",
    ".jsbeautifyrc",
    "flask/**",
    "tests/**",
    "docs/**",
    "nginx/**"
]

[tool.black.format]
color = true
